name = "high-signal-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SAASMAKER_API_KEY = "pk_3eb4816ef2179c25f364315aa1c3148a88e8004bfa5e5235"
